<?php
/*
 * Datei: fields_product_page.inc
 * Zweck: Definiert die Variablen und erstellt die zur Anzeige
 *        der Produktseite des Katalogs erforderlichenArrays
 */
$page = array(
    "title" => "Der Baumarkt - Katalog",
    "top" => "Der Baumarkt - Katalog",
    "bottom" => "Bei Fragen oder Problemen wenden Sie sich an admin@baumarkt.de"
);
$table_heads = array(
    "katalog_nr" => "Kat.Nr.",
    "name" => "Bezeichnung",
    "pr_beschr" => "Beschreibung",
    "preis" => "Preis",
    "menge" => "Menge"
);
?>