<?php
/*
 * Datei: fields_cart-oo.inc
 * Zweck: Enthaelt die zur Anzeige des Warenkorbes
 *        erforderlichen Daten
 */
$page = array(
    "title" => "Der Baumarkt - Warenkorb",
    "top" => "Der Baumarkt",
    "top2" => "Warenkorb",
    "bottom" => "Bei Fragen oder Problemen wenden Sie sich an admin@baumarkt.de"
);
$table_headers = array(
    "Pos.","Kat.Nr.","Bezeichnung","Menge",
    "Preis","Gesamt"
);
?>