<?php
/*
 * Datei: functions.inc
 * Zweck: Festlegung der Ländercodes für das
 *        Versandatenformular.
 */
function getStateCode()
{
    $stateCode = array( 1 => 
        "BE",
        "DA",
        "DE",
        "FO",
        "FI",
        "FR",
        "EL",
        "GA",
        "IT",
        "LI",
        "LU",
        "MO",
        "NL",
        "AT",
        "PL",
        "SV",
        "CH",
        "ES",
        "TR" );
    return $stateCode;
}
function getStateName()
{
    $stateName = array( 1 => 
        "Belgien",
        "D&auml;nemark",
        "Deutschland",
        "Far&ouml;er Inseln",
        "Finnland",
        "Frankreich",
        "Griechenland",
        "Irland",
        "Italien",
        "Liechtenstein",
        "Luxenburg",
        "Monaco",
        "Niederlande",
        "&Ouml;sterreich",
        "Polen",
        "Schweden",
        "Schweiz",
        "Spanien",
        "Tuuml;rkei" );
    return $stateName;
}
?>